package com.briup.dao;

import com.briup.bean.CstLog;
import com.briup.bean.CstLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CstLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOG
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    long countByExample(CstLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOG
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int deleteByExample(CstLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOG
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int deleteByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOG
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int insert(CstLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOG
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int insertSelective(CstLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOG
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    List<CstLog> selectByExample(CstLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOG
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    CstLog selectByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOG
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") CstLog record, @Param("example") CstLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOG
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int updateByExample(@Param("record") CstLog record, @Param("example") CstLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOG
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int updateByPrimaryKeySelective(CstLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOG
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int updateByPrimaryKey(CstLog record);
}