package com.briup.dao;

import com.briup.bean.OrdersLine;
import com.briup.bean.OrdersLineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdersLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS_LINE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    long countByExample(OrdersLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS_LINE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int deleteByExample(OrdersLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS_LINE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int deleteByPrimaryKey(Long oddId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS_LINE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int insert(OrdersLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS_LINE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int insertSelective(OrdersLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS_LINE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    List<OrdersLine> selectByExample(OrdersLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS_LINE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    OrdersLine selectByPrimaryKey(Long oddId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS_LINE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrdersLine record, @Param("example") OrdersLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS_LINE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int updateByExample(@Param("record") OrdersLine record, @Param("example") OrdersLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS_LINE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int updateByPrimaryKeySelective(OrdersLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS_LINE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int updateByPrimaryKey(OrdersLine record);
}