package com.briup.dao;

import com.briup.bean.Storage;
import com.briup.bean.StorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORAGE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    long countByExample(StorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORAGE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int deleteByExample(StorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORAGE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int insert(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORAGE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int insertSelective(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORAGE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    List<Storage> selectByExample(StorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORAGE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") Storage record, @Param("example") StorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORAGE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    int updateByExample(@Param("record") Storage record, @Param("example") StorageExample example);
}