package com.briup.bean;

import java.io.Serializable;

public class CstActivity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_ACTIVITY.ATV_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long atvId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_ACTIVITY.ATV_CUST_NO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String atvCustNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_ACTIVITY.ATV_CUST_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String atvCustName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_ACTIVITY.ATV_PLACE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String atvPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_ACTIVITY.ATV_TITLE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String atvTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_ACTIVITY.ATV_DESC
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String atvDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_ACTIVITY.ATV_CUST_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long atvCustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CST_ACTIVITY
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_ACTIVITY.ATV_ID
     *
     * @return the value of CST_ACTIVITY.ATV_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getAtvId() {
        return atvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_ACTIVITY.ATV_ID
     *
     * @param atvId the value for CST_ACTIVITY.ATV_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setAtvId(Long atvId) {
        this.atvId = atvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_ACTIVITY.ATV_CUST_NO
     *
     * @return the value of CST_ACTIVITY.ATV_CUST_NO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getAtvCustNo() {
        return atvCustNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_ACTIVITY.ATV_CUST_NO
     *
     * @param atvCustNo the value for CST_ACTIVITY.ATV_CUST_NO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setAtvCustNo(String atvCustNo) {
        this.atvCustNo = atvCustNo == null ? null : atvCustNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_ACTIVITY.ATV_CUST_NAME
     *
     * @return the value of CST_ACTIVITY.ATV_CUST_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getAtvCustName() {
        return atvCustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_ACTIVITY.ATV_CUST_NAME
     *
     * @param atvCustName the value for CST_ACTIVITY.ATV_CUST_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setAtvCustName(String atvCustName) {
        this.atvCustName = atvCustName == null ? null : atvCustName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_ACTIVITY.ATV_PLACE
     *
     * @return the value of CST_ACTIVITY.ATV_PLACE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getAtvPlace() {
        return atvPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_ACTIVITY.ATV_PLACE
     *
     * @param atvPlace the value for CST_ACTIVITY.ATV_PLACE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setAtvPlace(String atvPlace) {
        this.atvPlace = atvPlace == null ? null : atvPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_ACTIVITY.ATV_TITLE
     *
     * @return the value of CST_ACTIVITY.ATV_TITLE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getAtvTitle() {
        return atvTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_ACTIVITY.ATV_TITLE
     *
     * @param atvTitle the value for CST_ACTIVITY.ATV_TITLE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setAtvTitle(String atvTitle) {
        this.atvTitle = atvTitle == null ? null : atvTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_ACTIVITY.ATV_DESC
     *
     * @return the value of CST_ACTIVITY.ATV_DESC
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getAtvDesc() {
        return atvDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_ACTIVITY.ATV_DESC
     *
     * @param atvDesc the value for CST_ACTIVITY.ATV_DESC
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setAtvDesc(String atvDesc) {
        this.atvDesc = atvDesc == null ? null : atvDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_ACTIVITY.ATV_CUST_ID
     *
     * @return the value of CST_ACTIVITY.ATV_CUST_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getAtvCustId() {
        return atvCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_ACTIVITY.ATV_CUST_ID
     *
     * @param atvCustId the value for CST_ACTIVITY.ATV_CUST_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setAtvCustId(Long atvCustId) {
        this.atvCustId = atvCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_ACTIVITY
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", atvId=").append(atvId);
        sb.append(", atvCustNo=").append(atvCustNo);
        sb.append(", atvCustName=").append(atvCustName);
        sb.append(", atvPlace=").append(atvPlace);
        sb.append(", atvTitle=").append(atvTitle);
        sb.append(", atvDesc=").append(atvDesc);
        sb.append(", atvCustId=").append(atvCustId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}