package com.briup.bean;

import java.io.Serializable;

public class CstCustomer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_ID
     *客户序号，主键生成
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_NO
     *客户编号
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String custNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_NAME
     *名称
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String custName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_REGION
     *地区
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String custRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_MANAGER_ID
     *客户经理id
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long custManagerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_MANAGER_NAME
     *客户经理名字
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String custManagerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_LEVEL
     *客户等级数字
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long custLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_LEVEL_LABEL
     *客户等级名称
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String custLevelLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_SATISFY
     *满意度
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Integer custSatisfy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_CREDIT
     *信誉度
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Integer custCredit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_ADDR
     *地址
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String custAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_ZIP
     *邮箱
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String custZip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_TEL
     *电话
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String custTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_FAX
     *传真
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String custFax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_WEBSITE
     *网址
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String custWebsite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_LICENCE_NO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String custLicenceNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_CHIEFTAIN
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String custChieftain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_BANKROLL
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long custBankroll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_TURNOVER
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long custTurnover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_BANK
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String custBank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_BANK_ACCOUNT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String custBankAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_LOCAL_TAX_NO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String custLocalTaxNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_NATIONAL_TAX_NO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String custNationalTaxNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_STATUS
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String custStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CST_CUSTOMER
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_ID
     *
     * @return the value of CST_CUSTOMER.CUST_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_ID
     *
     * @param custId the value for CST_CUSTOMER.CUST_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_NO
     *
     * @return the value of CST_CUSTOMER.CUST_NO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_NO
     *
     * @param custNo the value for CST_CUSTOMER.CUST_NO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo == null ? null : custNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_NAME
     *
     * @return the value of CST_CUSTOMER.CUST_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_NAME
     *
     * @param custName the value for CST_CUSTOMER.CUST_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_REGION
     *
     * @return the value of CST_CUSTOMER.CUST_REGION
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getCustRegion() {
        return custRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_REGION
     *
     * @param custRegion the value for CST_CUSTOMER.CUST_REGION
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustRegion(String custRegion) {
        this.custRegion = custRegion == null ? null : custRegion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_MANAGER_ID
     *
     * @return the value of CST_CUSTOMER.CUST_MANAGER_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getCustManagerId() {
        return custManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_MANAGER_ID
     *
     * @param custManagerId the value for CST_CUSTOMER.CUST_MANAGER_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustManagerId(Long custManagerId) {
        this.custManagerId = custManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_MANAGER_NAME
     *
     * @return the value of CST_CUSTOMER.CUST_MANAGER_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getCustManagerName() {
        return custManagerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_MANAGER_NAME
     *
     * @param custManagerName the value for CST_CUSTOMER.CUST_MANAGER_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustManagerName(String custManagerName) {
        this.custManagerName = custManagerName == null ? null : custManagerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_LEVEL
     *
     * @return the value of CST_CUSTOMER.CUST_LEVEL
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getCustLevel() {
        return custLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_LEVEL
     *
     * @param custLevel the value for CST_CUSTOMER.CUST_LEVEL
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustLevel(Long custLevel) {
        this.custLevel = custLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_LEVEL_LABEL
     *
     * @return the value of CST_CUSTOMER.CUST_LEVEL_LABEL
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getCustLevelLabel() {
        return custLevelLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_LEVEL_LABEL
     *
     * @param custLevelLabel the value for CST_CUSTOMER.CUST_LEVEL_LABEL
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustLevelLabel(String custLevelLabel) {
        this.custLevelLabel = custLevelLabel == null ? null : custLevelLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_SATISFY
     *
     * @return the value of CST_CUSTOMER.CUST_SATISFY
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Integer getCustSatisfy() {
        return custSatisfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_SATISFY
     *
     * @param custSatisfy the value for CST_CUSTOMER.CUST_SATISFY
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustSatisfy(Integer custSatisfy) {
        this.custSatisfy = custSatisfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_CREDIT
     *
     * @return the value of CST_CUSTOMER.CUST_CREDIT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Integer getCustCredit() {
        return custCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_CREDIT
     *
     * @param custCredit the value for CST_CUSTOMER.CUST_CREDIT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustCredit(Integer custCredit) {
        this.custCredit = custCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_ADDR
     *
     * @return the value of CST_CUSTOMER.CUST_ADDR
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getCustAddr() {
        return custAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_ADDR
     *
     * @param custAddr the value for CST_CUSTOMER.CUST_ADDR
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustAddr(String custAddr) {
        this.custAddr = custAddr == null ? null : custAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_ZIP
     *
     * @return the value of CST_CUSTOMER.CUST_ZIP
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getCustZip() {
        return custZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_ZIP
     *
     * @param custZip the value for CST_CUSTOMER.CUST_ZIP
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustZip(String custZip) {
        this.custZip = custZip == null ? null : custZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_TEL
     *
     * @return the value of CST_CUSTOMER.CUST_TEL
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getCustTel() {
        return custTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_TEL
     *
     * @param custTel the value for CST_CUSTOMER.CUST_TEL
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustTel(String custTel) {
        this.custTel = custTel == null ? null : custTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_FAX
     *
     * @return the value of CST_CUSTOMER.CUST_FAX
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getCustFax() {
        return custFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_FAX
     *
     * @param custFax the value for CST_CUSTOMER.CUST_FAX
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustFax(String custFax) {
        this.custFax = custFax == null ? null : custFax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_WEBSITE
     *
     * @return the value of CST_CUSTOMER.CUST_WEBSITE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getCustWebsite() {
        return custWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_WEBSITE
     *
     * @param custWebsite the value for CST_CUSTOMER.CUST_WEBSITE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustWebsite(String custWebsite) {
        this.custWebsite = custWebsite == null ? null : custWebsite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_LICENCE_NO
     *
     * @return the value of CST_CUSTOMER.CUST_LICENCE_NO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getCustLicenceNo() {
        return custLicenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_LICENCE_NO
     *
     * @param custLicenceNo the value for CST_CUSTOMER.CUST_LICENCE_NO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustLicenceNo(String custLicenceNo) {
        this.custLicenceNo = custLicenceNo == null ? null : custLicenceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_CHIEFTAIN
     *
     * @return the value of CST_CUSTOMER.CUST_CHIEFTAIN
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getCustChieftain() {
        return custChieftain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_CHIEFTAIN
     *
     * @param custChieftain the value for CST_CUSTOMER.CUST_CHIEFTAIN
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustChieftain(String custChieftain) {
        this.custChieftain = custChieftain == null ? null : custChieftain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_BANKROLL
     *
     * @return the value of CST_CUSTOMER.CUST_BANKROLL
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getCustBankroll() {
        return custBankroll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_BANKROLL
     *
     * @param custBankroll the value for CST_CUSTOMER.CUST_BANKROLL
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustBankroll(Long custBankroll) {
        this.custBankroll = custBankroll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_TURNOVER
     *
     * @return the value of CST_CUSTOMER.CUST_TURNOVER
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getCustTurnover() {
        return custTurnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_TURNOVER
     *
     * @param custTurnover the value for CST_CUSTOMER.CUST_TURNOVER
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustTurnover(Long custTurnover) {
        this.custTurnover = custTurnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_BANK
     *
     * @return the value of CST_CUSTOMER.CUST_BANK
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getCustBank() {
        return custBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_BANK
     *
     * @param custBank the value for CST_CUSTOMER.CUST_BANK
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustBank(String custBank) {
        this.custBank = custBank == null ? null : custBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_BANK_ACCOUNT
     *
     * @return the value of CST_CUSTOMER.CUST_BANK_ACCOUNT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getCustBankAccount() {
        return custBankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_BANK_ACCOUNT
     *
     * @param custBankAccount the value for CST_CUSTOMER.CUST_BANK_ACCOUNT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustBankAccount(String custBankAccount) {
        this.custBankAccount = custBankAccount == null ? null : custBankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_LOCAL_TAX_NO
     *
     * @return the value of CST_CUSTOMER.CUST_LOCAL_TAX_NO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getCustLocalTaxNo() {
        return custLocalTaxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_LOCAL_TAX_NO
     *
     * @param custLocalTaxNo the value for CST_CUSTOMER.CUST_LOCAL_TAX_NO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustLocalTaxNo(String custLocalTaxNo) {
        this.custLocalTaxNo = custLocalTaxNo == null ? null : custLocalTaxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_NATIONAL_TAX_NO
     *
     * @return the value of CST_CUSTOMER.CUST_NATIONAL_TAX_NO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getCustNationalTaxNo() {
        return custNationalTaxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_NATIONAL_TAX_NO
     *
     * @param custNationalTaxNo the value for CST_CUSTOMER.CUST_NATIONAL_TAX_NO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustNationalTaxNo(String custNationalTaxNo) {
        this.custNationalTaxNo = custNationalTaxNo == null ? null : custNationalTaxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_STATUS
     *
     * @return the value of CST_CUSTOMER.CUST_STATUS
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getCustStatus() {
        return custStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_STATUS
     *
     * @param custStatus the value for CST_CUSTOMER.CUST_STATUS
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setCustStatus(String custStatus) {
        this.custStatus = custStatus == null ? null : custStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_CUSTOMER
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", custId=").append(custId);
        sb.append(", custNo=").append(custNo);
        sb.append(", custName=").append(custName);
        sb.append(", custRegion=").append(custRegion);
        sb.append(", custManagerId=").append(custManagerId);
        sb.append(", custManagerName=").append(custManagerName);
        sb.append(", custLevel=").append(custLevel);
        sb.append(", custLevelLabel=").append(custLevelLabel);
        sb.append(", custSatisfy=").append(custSatisfy);
        sb.append(", custCredit=").append(custCredit);
        sb.append(", custAddr=").append(custAddr);
        sb.append(", custZip=").append(custZip);
        sb.append(", custTel=").append(custTel);
        sb.append(", custFax=").append(custFax);
        sb.append(", custWebsite=").append(custWebsite);
        sb.append(", custLicenceNo=").append(custLicenceNo);
        sb.append(", custChieftain=").append(custChieftain);
        sb.append(", custBankroll=").append(custBankroll);
        sb.append(", custTurnover=").append(custTurnover);
        sb.append(", custBank=").append(custBank);
        sb.append(", custBankAccount=").append(custBankAccount);
        sb.append(", custLocalTaxNo=").append(custLocalTaxNo);
        sb.append(", custNationalTaxNo=").append(custNationalTaxNo);
        sb.append(", custStatus=").append(custStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}