package com.briup.bean;

import java.io.Serializable;

public class CstLinkman implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_LINKMAN.LKM_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long lkmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_LINKMAN.LKM_CUST_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long lkmCustId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_LINKMAN.LKM_CUST_NO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String lkmCustNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_LINKMAN.LKM_CUST_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String lkmCustName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_LINKMAN.LKM_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String lkmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_LINKMAN.LKM_SEX
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String lkmSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_LINKMAN.LKM_POSTION
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String lkmPostion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_LINKMAN.LKM_TEL
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String lkmTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_LINKMAN.LKM_MOBILE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String lkmMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_LINKMAN.LKM_MEMO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String lkmMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CST_LINKMAN
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LINKMAN.LKM_ID
     *
     * @return the value of CST_LINKMAN.LKM_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getLkmId() {
        return lkmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LINKMAN.LKM_ID
     *
     * @param lkmId the value for CST_LINKMAN.LKM_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setLkmId(Long lkmId) {
        this.lkmId = lkmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LINKMAN.LKM_CUST_ID
     *
     * @return the value of CST_LINKMAN.LKM_CUST_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getLkmCustId() {
        return lkmCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LINKMAN.LKM_CUST_ID
     *
     * @param lkmCustId the value for CST_LINKMAN.LKM_CUST_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setLkmCustId(Long lkmCustId) {
        this.lkmCustId = lkmCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LINKMAN.LKM_CUST_NO
     *
     * @return the value of CST_LINKMAN.LKM_CUST_NO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getLkmCustNo() {
        return lkmCustNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LINKMAN.LKM_CUST_NO
     *
     * @param lkmCustNo the value for CST_LINKMAN.LKM_CUST_NO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setLkmCustNo(String lkmCustNo) {
        this.lkmCustNo = lkmCustNo == null ? null : lkmCustNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LINKMAN.LKM_CUST_NAME
     *
     * @return the value of CST_LINKMAN.LKM_CUST_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getLkmCustName() {
        return lkmCustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LINKMAN.LKM_CUST_NAME
     *
     * @param lkmCustName the value for CST_LINKMAN.LKM_CUST_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setLkmCustName(String lkmCustName) {
        this.lkmCustName = lkmCustName == null ? null : lkmCustName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LINKMAN.LKM_NAME
     *
     * @return the value of CST_LINKMAN.LKM_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getLkmName() {
        return lkmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LINKMAN.LKM_NAME
     *
     * @param lkmName the value for CST_LINKMAN.LKM_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setLkmName(String lkmName) {
        this.lkmName = lkmName == null ? null : lkmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LINKMAN.LKM_SEX
     *
     * @return the value of CST_LINKMAN.LKM_SEX
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getLkmSex() {
        return lkmSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LINKMAN.LKM_SEX
     *
     * @param lkmSex the value for CST_LINKMAN.LKM_SEX
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setLkmSex(String lkmSex) {
        this.lkmSex = lkmSex == null ? null : lkmSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LINKMAN.LKM_POSTION
     *
     * @return the value of CST_LINKMAN.LKM_POSTION
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getLkmPostion() {
        return lkmPostion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LINKMAN.LKM_POSTION
     *
     * @param lkmPostion the value for CST_LINKMAN.LKM_POSTION
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setLkmPostion(String lkmPostion) {
        this.lkmPostion = lkmPostion == null ? null : lkmPostion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LINKMAN.LKM_TEL
     *
     * @return the value of CST_LINKMAN.LKM_TEL
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getLkmTel() {
        return lkmTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LINKMAN.LKM_TEL
     *
     * @param lkmTel the value for CST_LINKMAN.LKM_TEL
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setLkmTel(String lkmTel) {
        this.lkmTel = lkmTel == null ? null : lkmTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LINKMAN.LKM_MOBILE
     *
     * @return the value of CST_LINKMAN.LKM_MOBILE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getLkmMobile() {
        return lkmMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LINKMAN.LKM_MOBILE
     *
     * @param lkmMobile the value for CST_LINKMAN.LKM_MOBILE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setLkmMobile(String lkmMobile) {
        this.lkmMobile = lkmMobile == null ? null : lkmMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LINKMAN.LKM_MEMO
     *
     * @return the value of CST_LINKMAN.LKM_MEMO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getLkmMemo() {
        return lkmMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LINKMAN.LKM_MEMO
     *
     * @param lkmMemo the value for CST_LINKMAN.LKM_MEMO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setLkmMemo(String lkmMemo) {
        this.lkmMemo = lkmMemo == null ? null : lkmMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LINKMAN
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lkmId=").append(lkmId);
        sb.append(", lkmCustId=").append(lkmCustId);
        sb.append(", lkmCustNo=").append(lkmCustNo);
        sb.append(", lkmCustName=").append(lkmCustName);
        sb.append(", lkmName=").append(lkmName);
        sb.append(", lkmSex=").append(lkmSex);
        sb.append(", lkmPostion=").append(lkmPostion);
        sb.append(", lkmTel=").append(lkmTel);
        sb.append(", lkmMobile=").append(lkmMobile);
        sb.append(", lkmMemo=").append(lkmMemo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}