package com.briup.bean;

import java.io.Serializable;

public class CstService implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_SERVICE.SVR_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long svrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_SERVICE.SVR_TYPE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String svrType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_SERVICE.SVR_TITLE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String svrTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_SERVICE.SVR_CUST_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String svrCustName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_SERVICE.SVR_STATUS
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String svrStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_SERVICE.SVR_REQUEST
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String svrRequest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_SERVICE.SVR_CREATE_BY
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String svrCreateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_SERVICE.SVR_DUE_TO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String svrDueTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_SERVICE.SVR_DEAL
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String svrDeal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_SERVICE.SVR_RESULT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String svrResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_SERVICE.SVR_SATISFY
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long svrSatisfy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CST_SERVICE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_ID
     *
     * @return the value of CST_SERVICE.SVR_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getSvrId() {
        return svrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_ID
     *
     * @param svrId the value for CST_SERVICE.SVR_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setSvrId(Long svrId) {
        this.svrId = svrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_TYPE
     *
     * @return the value of CST_SERVICE.SVR_TYPE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getSvrType() {
        return svrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_TYPE
     *
     * @param svrType the value for CST_SERVICE.SVR_TYPE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setSvrType(String svrType) {
        this.svrType = svrType == null ? null : svrType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_TITLE
     *
     * @return the value of CST_SERVICE.SVR_TITLE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getSvrTitle() {
        return svrTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_TITLE
     *
     * @param svrTitle the value for CST_SERVICE.SVR_TITLE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setSvrTitle(String svrTitle) {
        this.svrTitle = svrTitle == null ? null : svrTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_CUST_NAME
     *
     * @return the value of CST_SERVICE.SVR_CUST_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getSvrCustName() {
        return svrCustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_CUST_NAME
     *
     * @param svrCustName the value for CST_SERVICE.SVR_CUST_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setSvrCustName(String svrCustName) {
        this.svrCustName = svrCustName == null ? null : svrCustName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_STATUS
     *
     * @return the value of CST_SERVICE.SVR_STATUS
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getSvrStatus() {
        return svrStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_STATUS
     *
     * @param svrStatus the value for CST_SERVICE.SVR_STATUS
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setSvrStatus(String svrStatus) {
        this.svrStatus = svrStatus == null ? null : svrStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_REQUEST
     *
     * @return the value of CST_SERVICE.SVR_REQUEST
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getSvrRequest() {
        return svrRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_REQUEST
     *
     * @param svrRequest the value for CST_SERVICE.SVR_REQUEST
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setSvrRequest(String svrRequest) {
        this.svrRequest = svrRequest == null ? null : svrRequest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_CREATE_BY
     *
     * @return the value of CST_SERVICE.SVR_CREATE_BY
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getSvrCreateBy() {
        return svrCreateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_CREATE_BY
     *
     * @param svrCreateBy the value for CST_SERVICE.SVR_CREATE_BY
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setSvrCreateBy(String svrCreateBy) {
        this.svrCreateBy = svrCreateBy == null ? null : svrCreateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_DUE_TO
     *
     * @return the value of CST_SERVICE.SVR_DUE_TO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getSvrDueTo() {
        return svrDueTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_DUE_TO
     *
     * @param svrDueTo the value for CST_SERVICE.SVR_DUE_TO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setSvrDueTo(String svrDueTo) {
        this.svrDueTo = svrDueTo == null ? null : svrDueTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_DEAL
     *
     * @return the value of CST_SERVICE.SVR_DEAL
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getSvrDeal() {
        return svrDeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_DEAL
     *
     * @param svrDeal the value for CST_SERVICE.SVR_DEAL
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setSvrDeal(String svrDeal) {
        this.svrDeal = svrDeal == null ? null : svrDeal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_RESULT
     *
     * @return the value of CST_SERVICE.SVR_RESULT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getSvrResult() {
        return svrResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_RESULT
     *
     * @param svrResult the value for CST_SERVICE.SVR_RESULT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setSvrResult(String svrResult) {
        this.svrResult = svrResult == null ? null : svrResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_SATISFY
     *
     * @return the value of CST_SERVICE.SVR_SATISFY
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getSvrSatisfy() {
        return svrSatisfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_SATISFY
     *
     * @param svrSatisfy the value for CST_SERVICE.SVR_SATISFY
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setSvrSatisfy(Long svrSatisfy) {
        this.svrSatisfy = svrSatisfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_SERVICE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", svrId=").append(svrId);
        sb.append(", svrType=").append(svrType);
        sb.append(", svrTitle=").append(svrTitle);
        sb.append(", svrCustName=").append(svrCustName);
        sb.append(", svrStatus=").append(svrStatus);
        sb.append(", svrRequest=").append(svrRequest);
        sb.append(", svrCreateBy=").append(svrCreateBy);
        sb.append(", svrDueTo=").append(svrDueTo);
        sb.append(", svrDeal=").append(svrDeal);
        sb.append(", svrResult=").append(svrResult);
        sb.append(", svrSatisfy=").append(svrSatisfy);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}