package com.briup.bean;

import java.io.Serializable;

public class OrdersLine implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS_LINE.ODD_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long oddId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS_LINE.ODD_ORDER_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long oddOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS_LINE.ODD_COUNT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long oddCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS_LINE.ODD_UNIT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String oddUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS_LINE.ODD_PRICE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long oddPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS_LINE.PROD_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long prodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ORDERS_LINE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS_LINE.ODD_ID
     *
     * @return the value of ORDERS_LINE.ODD_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getOddId() {
        return oddId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS_LINE.ODD_ID
     *
     * @param oddId the value for ORDERS_LINE.ODD_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setOddId(Long oddId) {
        this.oddId = oddId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS_LINE.ODD_ORDER_ID
     *
     * @return the value of ORDERS_LINE.ODD_ORDER_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getOddOrderId() {
        return oddOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS_LINE.ODD_ORDER_ID
     *
     * @param oddOrderId the value for ORDERS_LINE.ODD_ORDER_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setOddOrderId(Long oddOrderId) {
        this.oddOrderId = oddOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS_LINE.ODD_COUNT
     *
     * @return the value of ORDERS_LINE.ODD_COUNT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getOddCount() {
        return oddCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS_LINE.ODD_COUNT
     *
     * @param oddCount the value for ORDERS_LINE.ODD_COUNT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setOddCount(Long oddCount) {
        this.oddCount = oddCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS_LINE.ODD_UNIT
     *
     * @return the value of ORDERS_LINE.ODD_UNIT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getOddUnit() {
        return oddUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS_LINE.ODD_UNIT
     *
     * @param oddUnit the value for ORDERS_LINE.ODD_UNIT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setOddUnit(String oddUnit) {
        this.oddUnit = oddUnit == null ? null : oddUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS_LINE.ODD_PRICE
     *
     * @return the value of ORDERS_LINE.ODD_PRICE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getOddPrice() {
        return oddPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS_LINE.ODD_PRICE
     *
     * @param oddPrice the value for ORDERS_LINE.ODD_PRICE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setOddPrice(Long oddPrice) {
        this.oddPrice = oddPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS_LINE.PROD_ID
     *
     * @return the value of ORDERS_LINE.PROD_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS_LINE.PROD_ID
     *
     * @param prodId the value for ORDERS_LINE.PROD_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setProdId(Long prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS_LINE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", oddId=").append(oddId);
        sb.append(", oddOrderId=").append(oddOrderId);
        sb.append(", oddCount=").append(oddCount);
        sb.append(", oddUnit=").append(oddUnit);
        sb.append(", oddPrice=").append(oddPrice);
        sb.append(", prodId=").append(prodId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}