package com.briup.bean;

import java.io.Serializable;

public class Product implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PROD_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long prodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PROD_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String prodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PROD_TYPE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String prodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PROD_BATCH
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String prodBatch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PROD_UNIT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String prodUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PROD_PRICE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long prodPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PROD_MEMO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String prodMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PRODUCT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PROD_ID
     *
     * @return the value of PRODUCT.PROD_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PROD_ID
     *
     * @param prodId the value for PRODUCT.PROD_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setProdId(Long prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PROD_NAME
     *
     * @return the value of PRODUCT.PROD_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PROD_NAME
     *
     * @param prodName the value for PRODUCT.PROD_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setProdName(String prodName) {
        this.prodName = prodName == null ? null : prodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PROD_TYPE
     *
     * @return the value of PRODUCT.PROD_TYPE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getProdType() {
        return prodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PROD_TYPE
     *
     * @param prodType the value for PRODUCT.PROD_TYPE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setProdType(String prodType) {
        this.prodType = prodType == null ? null : prodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PROD_BATCH
     *
     * @return the value of PRODUCT.PROD_BATCH
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getProdBatch() {
        return prodBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PROD_BATCH
     *
     * @param prodBatch the value for PRODUCT.PROD_BATCH
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setProdBatch(String prodBatch) {
        this.prodBatch = prodBatch == null ? null : prodBatch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PROD_UNIT
     *
     * @return the value of PRODUCT.PROD_UNIT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getProdUnit() {
        return prodUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PROD_UNIT
     *
     * @param prodUnit the value for PRODUCT.PROD_UNIT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setProdUnit(String prodUnit) {
        this.prodUnit = prodUnit == null ? null : prodUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PROD_PRICE
     *
     * @return the value of PRODUCT.PROD_PRICE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getProdPrice() {
        return prodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PROD_PRICE
     *
     * @param prodPrice the value for PRODUCT.PROD_PRICE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setProdPrice(Long prodPrice) {
        this.prodPrice = prodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PROD_MEMO
     *
     * @return the value of PRODUCT.PROD_MEMO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getProdMemo() {
        return prodMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PROD_MEMO
     *
     * @param prodMemo the value for PRODUCT.PROD_MEMO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setProdMemo(String prodMemo) {
        this.prodMemo = prodMemo == null ? null : prodMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", prodId=").append(prodId);
        sb.append(", prodName=").append(prodName);
        sb.append(", prodType=").append(prodType);
        sb.append(", prodBatch=").append(prodBatch);
        sb.append(", prodUnit=").append(prodUnit);
        sb.append(", prodPrice=").append(prodPrice);
        sb.append(", prodMemo=").append(prodMemo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}