package com.briup.bean;

import java.io.Serializable;

public class SalChance implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAL_CHANCE.CHC_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long chcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAL_CHANCE.CHC_SOURCE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String chcSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAL_CHANCE.CHC_CUST_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String chcCustName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAL_CHANCE.CHC_TITLE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String chcTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAL_CHANCE.CHC_RATE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long chcRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAL_CHANCE.CHC_LINKMAN
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String chcLinkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAL_CHANCE.CHC_TEL
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String chcTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAL_CHANCE.CHC_ADDR
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String chcAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAL_CHANCE.CHC_DESC
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String chcDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAL_CHANCE.CHC_CREATE_BY
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String chcCreateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAL_CHANCE.CHC_DUE_TO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String chcDueTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAL_CHANCE.CHC_STATUS
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String chcStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SAL_CHANCE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAL_CHANCE.CHC_ID
     *
     * @return the value of SAL_CHANCE.CHC_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getChcId() {
        return chcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAL_CHANCE.CHC_ID
     *
     * @param chcId the value for SAL_CHANCE.CHC_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setChcId(Long chcId) {
        this.chcId = chcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAL_CHANCE.CHC_SOURCE
     *
     * @return the value of SAL_CHANCE.CHC_SOURCE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getChcSource() {
        return chcSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAL_CHANCE.CHC_SOURCE
     *
     * @param chcSource the value for SAL_CHANCE.CHC_SOURCE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setChcSource(String chcSource) {
        this.chcSource = chcSource == null ? null : chcSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAL_CHANCE.CHC_CUST_NAME
     *
     * @return the value of SAL_CHANCE.CHC_CUST_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getChcCustName() {
        return chcCustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAL_CHANCE.CHC_CUST_NAME
     *
     * @param chcCustName the value for SAL_CHANCE.CHC_CUST_NAME
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setChcCustName(String chcCustName) {
        this.chcCustName = chcCustName == null ? null : chcCustName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAL_CHANCE.CHC_TITLE
     *
     * @return the value of SAL_CHANCE.CHC_TITLE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getChcTitle() {
        return chcTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAL_CHANCE.CHC_TITLE
     *
     * @param chcTitle the value for SAL_CHANCE.CHC_TITLE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setChcTitle(String chcTitle) {
        this.chcTitle = chcTitle == null ? null : chcTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAL_CHANCE.CHC_RATE
     *
     * @return the value of SAL_CHANCE.CHC_RATE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getChcRate() {
        return chcRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAL_CHANCE.CHC_RATE
     *
     * @param chcRate the value for SAL_CHANCE.CHC_RATE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setChcRate(Long chcRate) {
        this.chcRate = chcRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAL_CHANCE.CHC_LINKMAN
     *
     * @return the value of SAL_CHANCE.CHC_LINKMAN
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getChcLinkman() {
        return chcLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAL_CHANCE.CHC_LINKMAN
     *
     * @param chcLinkman the value for SAL_CHANCE.CHC_LINKMAN
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setChcLinkman(String chcLinkman) {
        this.chcLinkman = chcLinkman == null ? null : chcLinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAL_CHANCE.CHC_TEL
     *
     * @return the value of SAL_CHANCE.CHC_TEL
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getChcTel() {
        return chcTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAL_CHANCE.CHC_TEL
     *
     * @param chcTel the value for SAL_CHANCE.CHC_TEL
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setChcTel(String chcTel) {
        this.chcTel = chcTel == null ? null : chcTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAL_CHANCE.CHC_ADDR
     *
     * @return the value of SAL_CHANCE.CHC_ADDR
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getChcAddr() {
        return chcAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAL_CHANCE.CHC_ADDR
     *
     * @param chcAddr the value for SAL_CHANCE.CHC_ADDR
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setChcAddr(String chcAddr) {
        this.chcAddr = chcAddr == null ? null : chcAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAL_CHANCE.CHC_DESC
     *
     * @return the value of SAL_CHANCE.CHC_DESC
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getChcDesc() {
        return chcDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAL_CHANCE.CHC_DESC
     *
     * @param chcDesc the value for SAL_CHANCE.CHC_DESC
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setChcDesc(String chcDesc) {
        this.chcDesc = chcDesc == null ? null : chcDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAL_CHANCE.CHC_CREATE_BY
     *
     * @return the value of SAL_CHANCE.CHC_CREATE_BY
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getChcCreateBy() {
        return chcCreateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAL_CHANCE.CHC_CREATE_BY
     *
     * @param chcCreateBy the value for SAL_CHANCE.CHC_CREATE_BY
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setChcCreateBy(String chcCreateBy) {
        this.chcCreateBy = chcCreateBy == null ? null : chcCreateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAL_CHANCE.CHC_DUE_TO
     *
     * @return the value of SAL_CHANCE.CHC_DUE_TO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getChcDueTo() {
        return chcDueTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAL_CHANCE.CHC_DUE_TO
     *
     * @param chcDueTo the value for SAL_CHANCE.CHC_DUE_TO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setChcDueTo(String chcDueTo) {
        this.chcDueTo = chcDueTo == null ? null : chcDueTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAL_CHANCE.CHC_STATUS
     *
     * @return the value of SAL_CHANCE.CHC_STATUS
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getChcStatus() {
        return chcStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAL_CHANCE.CHC_STATUS
     *
     * @param chcStatus the value for SAL_CHANCE.CHC_STATUS
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setChcStatus(String chcStatus) {
        this.chcStatus = chcStatus == null ? null : chcStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAL_CHANCE
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", chcId=").append(chcId);
        sb.append(", chcSource=").append(chcSource);
        sb.append(", chcCustName=").append(chcCustName);
        sb.append(", chcTitle=").append(chcTitle);
        sb.append(", chcRate=").append(chcRate);
        sb.append(", chcLinkman=").append(chcLinkman);
        sb.append(", chcTel=").append(chcTel);
        sb.append(", chcAddr=").append(chcAddr);
        sb.append(", chcDesc=").append(chcDesc);
        sb.append(", chcCreateBy=").append(chcCreateBy);
        sb.append(", chcDueTo=").append(chcDueTo);
        sb.append(", chcStatus=").append(chcStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}