package com.briup.bean;

import java.io.Serializable;

public class SalPlan implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAL_PLAN.PLA_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long plaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAL_PLAN.PLA_CHC_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private Long plaChcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAL_PLAN.PLA_TODO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String plaTodo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAL_PLAN.PLA_RESULT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private String plaResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SAL_PLAN
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAL_PLAN.PLA_ID
     *
     * @return the value of SAL_PLAN.PLA_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getPlaId() {
        return plaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAL_PLAN.PLA_ID
     *
     * @param plaId the value for SAL_PLAN.PLA_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setPlaId(Long plaId) {
        this.plaId = plaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAL_PLAN.PLA_CHC_ID
     *
     * @return the value of SAL_PLAN.PLA_CHC_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public Long getPlaChcId() {
        return plaChcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAL_PLAN.PLA_CHC_ID
     *
     * @param plaChcId the value for SAL_PLAN.PLA_CHC_ID
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setPlaChcId(Long plaChcId) {
        this.plaChcId = plaChcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAL_PLAN.PLA_TODO
     *
     * @return the value of SAL_PLAN.PLA_TODO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getPlaTodo() {
        return plaTodo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAL_PLAN.PLA_TODO
     *
     * @param plaTodo the value for SAL_PLAN.PLA_TODO
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setPlaTodo(String plaTodo) {
        this.plaTodo = plaTodo == null ? null : plaTodo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAL_PLAN.PLA_RESULT
     *
     * @return the value of SAL_PLAN.PLA_RESULT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public String getPlaResult() {
        return plaResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAL_PLAN.PLA_RESULT
     *
     * @param plaResult the value for SAL_PLAN.PLA_RESULT
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    public void setPlaResult(String plaResult) {
        this.plaResult = plaResult == null ? null : plaResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAL_PLAN
     *
     * @mbg.generated Tue Oct 23 11:46:45 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", plaId=").append(plaId);
        sb.append(", plaChcId=").append(plaChcId);
        sb.append(", plaTodo=").append(plaTodo);
        sb.append(", plaResult=").append(plaResult);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}